# Generated by Django 3.1.4 on 2021-02-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titile',
            new_name='title',
        ),
    ]
