# Generated by Django 3.1.4 on 2021-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20210201_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statustemp',
            field=models.CharField(choices=[('C', 'create'), ('R', 'requested'), ('P', 'in progress'), ('W', 'review'), ('T', 'testing'), ('D', 'done')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='new_statustemp',
            field=models.CharField(choices=[('C', 'create'), ('R', 'requested'), ('P', 'in progress'), ('W', 'review'), ('T', 'testing'), ('D', 'done')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='old_statustemp',
            field=models.CharField(choices=[('C', 'create'), ('R', 'requested'), ('P', 'in progress'), ('W', 'review'), ('T', 'testing'), ('D', 'done')], default='C', max_length=1),
        ),
    ]
