# Generated by Django 3.1.4 on 2021-02-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210201_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='statustemp',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='new_statustemp',
        ),
        migrations.RemoveField(
            model_name='taskupdate',
            name='old_statustemp',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[('CREATE', 0), ('REQUESTED', 1), ('IN PROGRESS', 2), ('REVIEW', 3), ('TESTING', 4), ('DONE', 5)], default=1),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='new_status',
            field=models.IntegerField(choices=[('CREATE', 0), ('REQUESTED', 1), ('IN PROGRESS', 2), ('REVIEW', 3), ('TESTING', 4), ('DONE', 5)]),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='old_status',
            field=models.IntegerField(choices=[('CREATE', 0), ('REQUESTED', 1), ('IN PROGRESS', 2), ('REVIEW', 3), ('TESTING', 4), ('DONE', 5)]),
        ),
    ]
