# Generated by Django 3.1.4 on 2021-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20210201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATE'), (1, 'REQUEST'), (2, 'DESIGN'), (3, 'WRITE'), (4, 'REVIEW'), (5, 'TESTING'), (6, 'DONE')], default=1),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='new_status',
            field=models.IntegerField(choices=[(0, 'CREATE'), (1, 'REQUEST'), (2, 'DESIGN'), (3, 'WRITE'), (4, 'REVIEW'), (5, 'TESTING'), (6, 'DONE')]),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='old_status',
            field=models.IntegerField(choices=[(0, 'CREATE'), (1, 'REQUEST'), (2, 'DESIGN'), (3, 'WRITE'), (4, 'REVIEW'), (5, 'TESTING'), (6, 'DONE')]),
        ),
    ]
