# Generated by Django 3.1.4 on 2021-02-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_auto_20210203_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'CREATE'), (1, 'BACKLOG'), (2, 'DESIGN'), (3, 'WRITE'), (4, 'REVIEW'), (5, 'TESTING'), (6, 'DONE'), (7, 'HIDDEN'), (8, 'IN PROGRESS')])),
                ('time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.task')),
            ],
        ),
    ]
