# Generated by Django 3.1.4 on 2021-02-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_tasknotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskNotes',
            new_name='TaskNote',
        ),
    ]
