# Generated by Django 3.1.4 on 2021-02-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20210204_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasknote',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='taskupdate',
            options={'ordering': ['time']},
        ),
    ]
